name: Update CNAME records on digitalocean

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Update records on digital ocean
        run: |
          cd domains
          doctl compute domain records list cli.rs > /tmp/domain_records.txt
          for file in *; do
            cname=$(cat $file)
            echo $file
            echo $cname

            if ! grep -q "CNAME.*$file.*$cname" /tmp/domain_records.txt; then
              doctl compute domain records create cli.rs --record-type CNAME --record-name $file --record-data $cname.
            else
              echo "CNAME record for $file already exists, skipping..."
            fi
          done
